import unittest
from scr.invoice_handler.xml_parser_equipment import get_xml_equipment
from scr.data_class.XmlInvoiceEquipment import XmlInvoiceEquipment
from scr.data_class.XmlInvoiceHeader import XmlInvoiceHeader
from unittest.mock import Mock
from scr.helper_functions.einvoice_helper import read_xml_file_to_str


class TestXmlParserHeader(unittest.TestCase):
    def test_get_xml_equipment(self):
        m_cn_id = "6983825"
        xml_invoice_header = XmlInvoiceHeader(m_cn_id=m_cn_id)
        xml_test_equipment = read_xml_file_to_str('xml_files/first_equipment.xml')
        xml_invoice_equipment = get_xml_equipment(xml_text=xml_test_equipment,
                                                  xml_invoice_data=xml_invoice_header, logger=Mock())

        self.assertEqual(xml_invoice_equipment.get_xml_equipment_map(),
                         [{'M_CN_HEADER_ID': '6983825', 'POS_NUM': 1, 'POS_CODE': '71HH',
                           'POS_DESC': 'i5 eDrive40 Touring', 'POS_PRICE': 51919.62, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 51919.62},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 2, 'POS_CODE': '1L0475', 'POS_DESC': 'Saphirschwarz',
                           'POS_PRICE': 933.88, 'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 933.88},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 3, 'POS_CODE': '1PKSSW',
                           'POS_DESC': 'Binnenbekleding Veganza geperforeerd met', 'POS_PRICE': 0.0,
                           'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 4, 'POS_CODE': '1S0230', 'POS_DESC': 'Versie EU',
                           'POS_PRICE': 0.0, 'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 5, 'POS_CODE': '1S0248',
                           'POS_DESC': 'Verwarmd stuurwiel', 'POS_PRICE': 256.2, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 256.2}, {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 6, 'POS_CODE': '1S02PA',
                                                      'POS_DESC': 'Antidiefstalbouten', 'POS_PRICE': 0.0,
                                                      'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 7, 'POS_CODE': '1S02VB',
                           'POS_DESC': 'Weergave bandendruk', 'POS_PRICE': 0.0, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 0.0}, {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 8, 'POS_CODE': '1S02VC',
                                                    'POS_DESC': 'Bandenherstelkit', 'POS_PRICE': 0.0,
                                                    'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 9, 'POS_CODE': '1S0302', 'POS_DESC': 'Alarmsysteem',
                           'POS_PRICE': 0.0, 'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 10, 'POS_CODE': '1S0322',
                           'POS_DESC': 'Comforttoegang', 'POS_PRICE': 0.0, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 0.0}, {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 11, 'POS_CODE': '1S0337',
                                                    'POS_DESC': 'M Sportpakket', 'POS_PRICE': 2892.56,
                                                    'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 2892.56},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 12, 'POS_CODE': '1S033B',
                           'POS_DESC': 'M Sport Pack Pro', 'POS_PRICE': 1421.49, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 1421.49},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 13, 'POS_CODE': '1S03DP',
                           'POS_DESC': 'BMW Iconic Glow Exterieur Pack', 'POS_PRICE': 0.0, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 0.0}, {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 14, 'POS_CODE': '1S03M2',
                                                    'POS_DESC': 'M Sport remmen, rot', 'POS_PRICE': 0.0,
                                                    'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 15, 'POS_CODE': '1S03MF',
                           'POS_DESC': 'M Lights Shadow Line', 'POS_PRICE': 0.0, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 0.0}, {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 16, 'POS_CODE': '1S0402',
                                                    'POS_DESC': 'Panoramisch doorschijnend dak', 'POS_PRICE': 1371.9,
                                                    'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 1371.9},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 17, 'POS_CODE': '1S0420',
                           'POS_DESC': 'Zonnewerend glas achteraan', 'POS_PRICE': 487.6, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 487.6}, {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 18, 'POS_CODE': '1S0428',
                                                      'POS_DESC': 'Gevarendriehoek en verbandkist', 'POS_PRICE': 0.0,
                                                      'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 19, 'POS_CODE': '1S043R',
                           'POS_DESC': 'M Decoratieve lijsten in Aluminium Rhomb', 'POS_PRICE': 0.0,
                           'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 20, 'POS_CODE': '1S0453',
                           'POS_DESC': 'Actieve zetelventilatie vooraan', 'POS_PRICE': 0.0, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 0.0}, {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 21, 'POS_CODE': '1S0459',
                                                    'POS_DESC': 'Elektrische regeling voorzetels met gehe',
                                                    'POS_PRICE': 0.0, 'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 22, 'POS_CODE': '1S0488',
                           'POS_DESC': 'Lendensteun vooraan', 'POS_PRICE': 0.0, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 0.0}, {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 23, 'POS_CODE': '1S04FL',
                                                    'POS_DESC': 'Travel & Comfort System', 'POS_PRICE': 0.0,
                                                    'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 24, 'POS_CODE': '1S04GQ',
                           'POS_DESC': 'M veiligheidsgordels', 'POS_PRICE': 0.0, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 0.0}, {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 25, 'POS_CODE': '1S04HA',
                                                    'POS_DESC': 'Verwarmde zetels vooraan en achteraan',
                                                    'POS_PRICE': 0.0, 'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 26, 'POS_CODE': '1S04NB',
                           'POS_DESC': 'Elektronisch gestuurde airconditioning,4', 'POS_PRICE': 0.0,
                           'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 27, 'POS_CODE': '1S04NR',
                           'POS_DESC': 'Interieurcamera', 'POS_PRICE': 0.0, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 0.0}, {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 28, 'POS_CODE': '1S04T2',
                                                    'POS_DESC': 'Snellaadkabel tot 22kW (Mode 3)', 'POS_PRICE': 0.0,
                                                    'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 29, 'POS_CODE': '1S04U9',
                           'POS_DESC': 'Akoestische voetgangersbescherming', 'POS_PRICE': 0.0, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 0.0}, {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 30, 'POS_CODE': '1S04UR',
                                                    'POS_DESC': 'Sfeerverlichting', 'POS_PRICE': 0.0,
                                                    'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 31, 'POS_CODE': '1S04V1',
                           'POS_DESC': 'BMW IconicSounds Electric', 'POS_PRICE': 0.0, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 0.0}, {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 32, 'POS_CODE': '1S0548',
                                                    'POS_DESC': 'Kilometertacho', 'POS_PRICE': 0.0,
                                                    'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 33, 'POS_CODE': '1S0552',
                           'POS_DESC': 'Adaptive LED headlights', 'POS_PRICE': 0.0, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 0.0}, {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 34, 'POS_CODE': '1S05AS',
                                                    'POS_DESC': 'Driving Assistant Pack', 'POS_PRICE': 0.0,
                                                    'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 35, 'POS_CODE': '1S05AT',
                           'POS_DESC': 'Driving Assistant Pack Plus', 'POS_PRICE': 950.41, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 950.41},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 36, 'POS_CODE': '1S05AV', 'POS_DESC': 'Active Guard',
                           'POS_PRICE': 0.0, 'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 37, 'POS_CODE': '1S05DN',
                           'POS_DESC': 'Parking Assistant Pack Plus', 'POS_PRICE': 0.0, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 38, 'POS_CODE': '1S0654', 'POS_DESC': 'DAB-Tuner',
                           'POS_PRICE': 0.0, 'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 39, 'POS_CODE': '1S0674',
                           'POS_DESC': 'Harman-Kardon sound system', 'POS_PRICE': 0.0, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 0.0}, {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 40, 'POS_CODE': '1S06AE',
                                                    'POS_DESC': 'BMW Teleservices', 'POS_PRICE': 0.0,
                                                    'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 41, 'POS_CODE': '1S06AF',
                           'POS_DESC': 'Intelligent Emergency Call - eCall', 'POS_PRICE': 0.0, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 0.0}, {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 42, 'POS_CODE': '1S06AK',
                                                    'POS_DESC': 'ConnectedDrive Services', 'POS_PRICE': 0.0,
                                                    'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 43, 'POS_CODE': '1S06C4',
                           'POS_DESC': 'ConnectedPackage Professional', 'POS_PRICE': 0.0, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 0.0}, {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 44, 'POS_CODE': '1S06NX',
                                                    'POS_DESC': 'Opbergvak voor Wireless Charging', 'POS_PRICE': 0.0,
                                                    'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 45, 'POS_CODE': '1S06PA',
                           'POS_DESC': 'Personal eSIM', 'POS_PRICE': 0.0, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 0.0}, {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 46, 'POS_CODE': '1S06U3',
                                                    'POS_DESC': 'BMW Live Cockpit Navigation Professional',
                                                    'POS_PRICE': 0.0, 'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 47, 'POS_CODE': '1S06U7',
                           'POS_DESC': 'BMW Natural Interaction', 'POS_PRICE': 0.0, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 0.0}, {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 48, 'POS_CODE': '1S0704',
                                                    'POS_DESC': 'M sportophanging', 'POS_PRICE': 0.0,
                                                    'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 49, 'POS_CODE': '1S0710', 'POS_DESC': 'M sportstuur',
                           'POS_PRICE': 0.0, 'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 50, 'POS_CODE': '1S0760',
                           'POS_DESC': 'M Shadow Line hochgl{nzend', 'POS_PRICE': 0.0, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 0.0}, {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 51, 'POS_CODE': '1S0775',
                                                    'POS_DESC': 'M Hemelbekleding Anthrazit', 'POS_PRICE': 0.0,
                                                    'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 52, 'POS_CODE': '1S07CG',
                           'POS_DESC': 'Garantie 3 jaar, zonder kilometerbeperki', 'POS_PRICE': 0.0,
                           'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 53, 'POS_CODE': '1S07EW',
                           'POS_DESC': 'Professional Pack', 'POS_PRICE': 1797.52, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 1797.52},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 54, 'POS_CODE': '1S07LK',
                           'POS_DESC': 'Advantage Plus Pack', 'POS_PRICE': 888.43, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 888.43}, {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 55, 'POS_CODE': '1S07M9',
                                                       'POS_DESC': 'M Shadow Line hochgl{nzend met bijkomend',
                                                       'POS_PRICE': 0.0, 'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 56, 'POS_CODE': '1S07VB', 'POS_DESC': 'Comfort Pack',
                           'POS_PRICE': 2314.05, 'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 2314.05},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 57, 'POS_CODE': '1S0851',
                           'POS_DESC': 'Spraakversie Duits', 'POS_PRICE': 0.0, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 0.0}, {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 58, 'POS_CODE': '1S0886',
                                                    'POS_DESC': 'Handleiding Nederlands', 'POS_PRICE': 0.0,
                                                    'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 59, 'POS_CODE': '1S08R3', 'POS_DESC': 'Interne code',
                           'POS_PRICE': 0.0, 'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 60, 'POS_CODE': '1S08R9', 'POS_DESC': 'Koelmiddel',
                           'POS_PRICE': 0.0, 'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 61, 'POS_CODE': '1S08TF',
                           'POS_DESC': 'Actieve voetgangersbescherming', 'POS_PRICE': 0.0, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 62, 'POS_CODE': '1S08WC', 'POS_DESC': 'Interne code',
                           'POS_PRICE': 0.0, 'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 63, 'POS_CODE': '1S08WN', 'POS_DESC': 'Interne code',
                           'POS_PRICE': 0.0, 'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 64, 'POS_CODE': '1S0931',
                           'POS_DESC': 'Winterbanden i.p.v. zomerbanden', 'POS_PRICE': 0.0, 'POS_PRICE_PAID': None,
                           'POS_MSRP_PRICE': 0.0}, {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 65, 'POS_CODE': '1S09T1',
                                                    'POS_DESC': 'Specifieke exterieur elementen M Sport',
                                                    'POS_PRICE': 0.0, 'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 66, 'POS_CODE': '1S09T2',
                           'POS_DESC': 'Specifieke interieur elementen M Sport', 'POS_PRICE': 0.0,
                           'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0},
                          {'M_CN_HEADER_ID': '6983825', 'POS_NUM': 67, 'POS_CODE': '1S09TB',
                           'POS_DESC': 'Specifieke bijkomende elementen M SportP', 'POS_PRICE': 0.0,
                           'POS_PRICE_PAID': None, 'POS_MSRP_PRICE': 0.0}]

                         )


if __name__ == '__main__':
    unittest.main()
